export const TEEN_ROUTES = {
  room: '/(teen)/room',
  pages: '/(teen)/pages',
  calm: '/(teen)/calm',
  circle: '/(teen)/circle',
  voiceBip: '/(teen)/voicebip',
  cloud: '/(teen)/cloud',
  comfort: '/(teen)/comfort',
  crew: '/(teen)/crew',
  settings: '/(teen)/settings',
  more: '/(teen)/more',
  points: '/(teen)/points',
  history: '/(teen)/history',
  bridge: '/(teen)/bridge',
  s2tell: '/(teen)/bridge?compose=true',
  periodCalendar: '/(teen)/period-calendar',
  discover: '/(teen)/discover',
  profile: '/(teen)/profile',
  companionPicker: '/(teen)/chat',
  userRoom: '/(teen)/user-room',
  bippin2: '/(teen)/bippin2',
  growth: '/(teen)/growth',
  mindReset: '/(teen)/mind-body-reset?mode=mindReset',
  bodyReset: '/(teen)/mind-body-reset?mode=bodyReset',
  parentLinkVerify: '/(auth)/parent-link-verify',
} as const;

export type TeenRouteKey = keyof typeof TEEN_ROUTES;
