create table if not exists public.control_room_issues (
  id uuid primary key default gen_random_uuid(),
  category text not null,
  severity text not null default 'info',
  status text not null default 'open',
  title text not null,
  summary text,
  suggested_fix text,
  affected_surface text,
  affected_users integer not null default 0,
  occurrence_count integer not null default 1,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  owner text,
  release text,
  metadata jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  source text not null default 'runtime',
  fingerprint text,
  linked_release text,
  assigned_to text,
  resolved_at timestamptz,
  resolved_by uuid references auth.users(id),
  notes text
);
